config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'sessions#new'
  
  get 'dashboard', to: 'dashboard#index'
  get 'universities', to: 'dashboard#unis'
  get 'admins', to: 'dashboard#admins'
  get 'students', to: 'dashboard#students'
  get 'events', to: 'dashboard#events'

  get 'overview', to: 'overview#index'
  
  get '/error', to: 'sessions#error'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/new/user', to: 'sessions#newUser'
  post '/new/user', to: 'users#create'
  get '/new/admin', to: 'dashboard#newAdmin'
  post '/new/admin', to: 'dashboard#createAdmin'

  get '/edit/admin', to: 'dashboard#editAdmin'
  post '/edit/admin', to: 'dashboard#updateAdmin'

  get '/user', to: 'dashboard#viewUser'
  delete '/user', to: 'dashboard#destroyUser'

  get '/landing', to: 'sessions#landing'

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include DashboardHelper
  include MailerHelper
  include UsersHelper
  layout 'dashboard'
  before_action :redirect_user
  before_action :require_admin, only: [:admins, :destroyUser, :unis]
  before_action :require_vorstand
  def index
  end

  def admins
    @users = User.all
  end

  def newAdmin
  end

  def editAdmin
    @user = User.find(params[:id])
  end

  def updateAdmin
    @user = User.find(params[:id])
    byebug
    if @user.update(user_params.except(:password, :password_confirmation))
      redirect_to admins_path, notice: 'Admin wurde aktualisiert.'
    else
      error_messages = @user.errors.full_messages.join(', ')
      redirect_to admins_path, notice: 'Admin konnte nicht aktualisiert werden: ' + error_messages
    end
  end

  def viewUser
    @user = User.find(params[:id])
    unless @user.listmonk_id == nil
      @mailingLists = getMailingLists(@user)
    else
      @mailingLists = "Keine"
    end
  end

  def createAdmin
    @user = User.new
    password = generate_password
    User.create(user_params, password: password, password_confirmation: password, paid: true)
    if @user.valid?
      @user.save
      addToMailingList(@user)
      redirect_to admins_path, notice: 'Admin wurde erstellt.'
    else
      error_messages = @user.errors.full_messages.join(', ')
      redirect_to admins_path, notice: 'Admin konnte nicht erstellt werden: ' + error_messages
    end
  end

  def destroyUser
    user = User.find(params[:id])
    if user.role == 3 && User.where(role: 3).count == 1
      redirect_to admins_path, notice: 'Es muss mindestens ein Admin existieren.'
      return
    end
    role = user.role
    user.destroy
    if role > 0
      redirect_to admins_path, notice: 'Benutzer wurde gelöscht.'
    else
      redirect_to students_path, notice: 'Benutzer wurde gelöscht.'
    end
  end

  def events
    @events = Event.all
  end

  def students
      @users = User.all.where(role: 0)
      @users = @users.where("name LIKE ?", "%#{params[:search]}%") if params[:search].present?
  end

  def unis
    @universities = University.all
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :role, :university_id)
  end
  
  def redirect_user
    if current_user && current_user.role == 0
      redirect_to overview_path
    end
  end

  def require_admin
    unless current_user && current_user.role == 3
      redirect_to dashboard_path, notice: 'Du hast nicht die nötigen Rechte um diese Seite zu sehen.'
    end
  end

  def require_vorstand
    unless current_user && current_user.role > 0
      redirect_to root_path, notice: 'Du hast nicht die nötigen Rechte um diese Seite zu sehen.'
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
    def generate_password
        chars = [('a'..'z'), ('A'..'Z'), (0..9)].map(&:to_a).flatten
        password = (0...12).map { chars[rand(chars.length)] }.join
    end

    def getMailingLists(user)
        url = ENV['LISTMONK_URL'] + "/api/subscribers/#{user.listmonk_id}"
        auth = {
            :username => ENV['LISTMONK_USERNAME'],
            :password => ENV['LISTMONK_PASSWORD']
        }
        response = HTTParty.get(url, basic_auth: auth)
        data = []
        for list in response["data"]["lists"]
            data.push(list["name"])
        end
        return data
    end
end

app/views/dashboard/admins.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex mb-2">
      <h5 class="card-title my-auto">Benutzer</h5>
      <div class="ms-auto">
        <%= link_to "Neuer Benutzer", new_admin_path, class: "btn btn-primary" %>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Email
          </th>
          <th>
            Rolle
          </th>
          <th>
            Aktionen
          </th>
        </tr>
      </thead>
      <tbody>
        <% @users.where("role > ?", 0).each do |user| %>
          <tr class="align-middle">
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= user.email %>
            </td>
            <td>
              <% if user.role == 1 %>
                Vorstand
              <% elsif user.role == 2 %>
                Kommunikation
              <% elsif user.role == 3 %>
                Admin
              <% else %>
                Unknown
              <% end %>
            </td>
            <td>
              <div class="dropdown">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Aktionen
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <li><%= link_to "Bearbeiten", edit_admin_path(id: user.id), class: "dropdown-item" %></li>
                  <li><%= button_to "Löschen", user_path, method: :delete, class: "dropdown-item text-danger", data: { confirm: "Are you sure you want to delete this user?" }, params: { id: user.id } %></li>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/dashboard/editAdmin.html.erb
<main class="w-100 m-auto border rounded shadow" style="max-width: 500px; padding: 15px;">
  <h4>Neuer Benutzer</h4>
  <%= form_with model: @user, url: "/edit/admin", method: "post" do |form| %>
    <%= hidden_field_tag :id, @user.id %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :Rolle, class: "form-label" %>
      <%= form.select :role, { "Vorstand"=> 1, "Kommunikation" => 2, "Admin" => 3 }, { selected: @user.role }, class: "form-select mb-3"
                    %>
    </div>
    <%= form.hidden_field_tag :password_digest, @user.password_digest %>
    <%= form.select :university_id, options_for_select(University.all.map { |u| [u.name, u.id] }, @user.university_id), class: "form-select mb-3" %>
    <%= form.submit "Speichern" , class: "btn btn-primary w-100" %>
  <% end %>
</main>

app/views/dashboard/events.html.erb
<main class="w-100 m-auto border rounded shadow" style="padding: 15px;">
        <div class="d-flex mb-2">
          <h5 class="card-title my-auto">Events</h5>
          <%= link_to bootstrap_icon("plus-lg"), new_user_path, class:"btn btn-primary ms-auto" %>
        </div>
</main>

app/views/dashboard/index.html.erb
  
<div class="row">
  <div class="col-md-6 mb-3">
    <div class="card">
      <div class="card-body">
        <div class="d-flex mb-2">
          <h5 class="card-title my-auto">Neuste Mitglieder:</h5>
          <%= link_to bootstrap_icon("plus-lg"), new_user_path, class:"btn btn-primary ms-auto d-inline-flex" %>
        </div>
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th>Name</th>
                <th>Email</th>
                <th>$$$</th>
              </tr>
            </thead>
            <tbody>
              <% User.where(role: 0).order(created_at: :desc).limit(5).each do |user| %>
                <tr>
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <% if user.paid %>
                    <td><%= bootstrap_icon "check" %></td>
                  <% else %>
                    <td><%= bootstrap_icon "x" %></td>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <%= link_to "Alle Mitglieder", students_path, class: "card-link" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Aktueller Status</h5>
        <p class="card-text">Anzahl Mitglieder: <%= User.where(role: 0).count %> </p>
        <p class="card-text">Aktive Mitglieder: <%= User.where(role: 0, paid: true).count %></p>
        <a href="#" class="card-link">Card link</a>
        <a href="#" class="card-link">Another link</a>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/newAdmin.html.erb
<main class="w-100 m-auto border rounded shadow" style="max-width: 500px; padding: 15px;">
  <h4>Neuer Benutzer</h4>
  <%= form_with url: "/new/admin", method: "post" do |form| %>
    <div class="mb-3">
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :email, class: "form-label" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    <div class="mb-3">
      <%= form.label :Rolle, class: "form-label" %>
      <%= form.select :role, { "Vorstand"=> 1, "Kommunikation" => 2, "Admin" => 3 }, {}, class: "form-select mb-3"
                    %>
    </div>
    <%= form.select :university_id, options_for_select(University.all.map { |u| [u.name, u.id] }), { include_blank: "Wähle eine Hochschule..." }, class: "form-select mb-3", id: "floatingUniversity" %>
    <%= form.submit "Create" , class: "btn btn-primary" %>
  <% end %>
</main>

app/views/dashboard/students.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex justify-content-between align-items-center">
      <h4 class="my-auto">Mitglieder</h4>
      <%= link_to bootstrap_icon("plus-lg"), new_user_path, class: "btn btn-primary" %>
    </div>
    <div class="my-2">
      <%= form_with(url: students_path, method: :get) do |form| %>
        <div class="my-auto input-group">
          <%= form.text_field :search, class: "form-control", placeholder: "Search by name" %>
          <button class="btn btn-outline-secondary" type="submit"><%= bootstrap_icon("search") %></button>
        </div>
      <% end %>
    </div>
    <div class="table-responsive">
      <table class="table table-hover table-striped table-bordered rounded mb-0">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th class="text-center">$$$</th>
            <th class="text-center">Aktionen</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |stud| %>
            <tr class="align-middle">
              <td><%= stud.name %></td>
              <td><%= stud.email %></td>
              <% if stud.paid %>
                <td class="text-success text-center"><%= bootstrap_icon "check" %></td>
              <% else %>
                <td class="text-danger text-center"><%= bootstrap_icon "x" %></td>
              <% end %>
              <td>
                <%= link_to bootstrap_icon("three-dots"), user_path(id: stud.id), class: "btn btn-sm btn-primary w-100" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboard/unis.html.erb
<div class="card">
  <div class="card-body">
    <div class="d-flex mb-2">
      <h5 class="card-title my-auto">Aktive Unis</h5>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Anzahl Studenten</th>
          </tr>
        </thead>
        <tbody>
          <% @universities.each do |uni| %>
            <tr class="align-middle">
              <td><%= uni.name %></td>
              <td> <%= User.where(university_id: uni.id).count %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/dashboard/viewUser.html.erb
<main class="w-100 m-auto border rounded shadow" style="max-width: 500px; padding: 15px;">
    <div class="d-flex">
  <%= link_to bootstrap_icon("arrow-left"), students_path, class: "btn" %><h4 class="align-middle my-auto"><%= @user.name %></h4>
  </div>
  <table class="table">
    <tbody>
      <tr>
        <th scope="row">Name</th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th scope="row">Email</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th scope="row">Angehörige Uni</th>
        <td><%= University.find(@user.university_id).name %></td>
      </tr>
      <tr>
        <th scope="row">Mitglieder Beitrag:</th>
        <% if @user.paid %>
          <td class="text-success"><%= bootstrap_icon("check") %></td>
        <% else %>
          <td class="text-danger"><%= bootstrap_icon("x") %> Noch nicht bezahlt!</td>
        <% end %>
      </tr>
      <tr>
        <th scope="row">Mailinglisten:</th>
        <td><%= @mailingLists %></td>
      <tr>
        <th scope="row">Mitglieder seit:</th>
        <td><%= @user.created_at.strftime("%d.%m.%Y") %></td>
    </tbody>
  </table>
  <div class="row g-2">
    <div class="col gx-2">
      <%= link_to bootstrap_icon("credit-card-fill") + " Zahlung", '#', class: "btn btn-primary w-100" %>
    </div>
    <div class="col gx-2">
      <%= link_to bootstrap_icon("pencil-fill") + " Bearbeiten", '#', class: "btn btn-primary w-100" %>
    </div>
    <div class="col gx-2">
      <%= button_to bootstrap_icon("trash-fill") + " Löschen", user_path(id: @user.id), method: :delete, class: "btn btn-danger w-100", data: { confirm: "Sind Sie sicher?" } %>
    </div>
  </div>
</main>