config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  root 'sessions#new'
  
  get 'dashboard', to: 'dashboard#index'
  get 'universities', to: 'dashboard#unis'
  get 'admins', to: 'dashboard#admins'
  get 'students', to: 'dashboard#students'
  get 'events', to: 'dashboard#events'

  get 'overview', to: 'overview#index'
  
  get '/error', to: 'sessions#error'
  post '/', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/new/user', to: 'sessions#newUser'
  post '/new/user', to: 'users#create'
  get '/new/admin', to: 'dashboard#newAdmin'
  post '/new/admin', to: 'dashboard#createAdmin'

  get '/edit/admin', to: 'dashboard#editAdmin'
  post '/edit/admin', to: 'dashboard#updateAdmin'

  get '/user', to: 'dashboard#viewUser'
  delete '/user', to: 'dashboard#destroyUser'

  get '/landing', to: 'sessions#landing'

  resources :password_resets, only: [:new, :create, :edit, :update]
end

app/views/layouts/_admin_dropdown.html.erb
<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    <%= current_user.name %>
</a>

<ul class="dropdown-menu">
    <li><%= link_to "Benutzer", admins_path, class: "dropdown-item" %>
    <li><%= link_to "Unis", universities_path, class: "dropdown-item" %>
    <li><%= button_to "Abmelden", logout_path, method: :delete, class: "dropdown-item" %></li>
</ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-3">
  <div class="container-md">
    <a class="navbar-brand" href="/dashboard">Bündnerclub Zürich</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(dashboard_path) %>" aria-current="page"
            href="<%= dashboard_path %>">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(students_path) %>" href="<%= students_path %>">Mitglieder</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(events_path) %>" href="<%= events_path %>">Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Statistik</a>
        </li>
      </ul>
      <ul class="navbar-nav d-flex flex-row">
        <li class="nav-item dropdown">
          <% if logged_in? %>
            <% if current_user.role==3%>
              <%= render "layouts/admin_dropdown" %>
            <% else %>
              <%= button_to "Abmelden", logout_path, method: :delete, class: "dropdown-item" %>
            <% end %>
          <% else %>
            <%= link_to "Not logged in" , root_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-bs-theme="light">
  <head>
    <title>UserTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= javascript_importmap_tags %>
  </head>
  <body class="<%= controller_name %>">
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html data-bs-theme="dark">
  <head>
    <title>UserTool</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "layouts/navigation" %>
    <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>